import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';

const SKETCHBOOK_URL =
  '/landing-pages/meng-to-sketchbook.html';

const SKETCHBOOK_ORIGIN =
  window.location.origin;

const MCA_EMBED_STYLE = `
  html,
  body {
    width: 100% !important;
    min-width: 0 !important;
    min-height: 100% !important;
    margin: 0 !important;
    padding: 0 !important;
    overflow-x: hidden !important;
    background: #ece7dc !important;
  }

  body {
    overflow-y: hidden !important;
  }

  /*
   * REMOVE ONLY THE ORIGINAL MENG TO
   * WEBSITE CONTENT.
   *
   * The actual Sketchbook and Plates
   * section are intentionally kept.
   */
  .wash,
  .top,
  .hero-kicker,
  .botany,
  .hero-down,
  .about,
  .foot {
    display: none !important;
  }

  /*
   * Remove decorative rules around
   * the sections we don't need.
   */
  .rule {
    display: none !important;
  }

  /*
   * IMPORTANT:
   *
   * The original Sketchbook has a
   * separate .sb-tilt layer around the
   * actual book.
   *
   * We freeze ONLY its X/Y rotation.
   *
   * The original zoom variable is kept,
   * so the existing zoom controls continue
   * to work.
   *
   * DO NOT change the page-turning
   * transform on .curl / .strip.
   */
  #sketchbook .sb-tilt {
    transform:
      rotateX(0deg)
      rotateY(0deg)
      scale(var(--zoom, 1)) !important;
  }

  /*
   * The original Sketchbook hero was
   * designed to fill the entire viewport.
   *
   * For our MCA page we make it a compact
   * book area so the Plates list follows
   * underneath.
   */
  .hero {
    width: 100% !important;
    min-width: 0 !important;
    min-height: 0 !important;
    height: auto !important;

    margin: 0 !important;
    padding: 0 0 8px !important;

    overflow: visible !important;

    display: grid !important;
    justify-items: center !important;
    align-content: center !important;
  }

  .sb-wrap {
    width: 100% !important;
    max-width: 900px !important;

    margin: 0 auto !important;

    display: grid !important;
    justify-items: center !important;

    gap: 16px !important;
  }

  .sb-stage {
    width: 100% !important;
    min-width: 0 !important;

    display: flex !important;
    align-items: center !important;
    justify-content: center !important;

    position: relative !important;
  }

  /*
   * Keep the original book maximum size.
   */
  .sb-3d {
    width: min(
      900px,
      calc(100vw - 76px)
    ) !important;

    max-width: 900px !important;

    flex: 0 1 900px !important;
  }

  .sb-book {
    width: 100% !important;
    max-width: 100% !important;
  }

  /*
   * Keep the entire photograph visible
   * instead of cropping its sides.
   */
  .sb-full {
    overflow: hidden !important;
  }

  .sb-full img {
    width: 100% !important;
    height: 100% !important;

    object-fit: contain !important;
    object-position: center !important;
  }

  .sb-half {
    overflow-x: clip !important;
    overflow-y: visible !important;
  }

  /*
   * The original caption/tools/hint
   * remain part of the Sketchbook.
   */
  .sb-captions {
    min-height: 18px !important;
  }

  /*
   * Plates are intentionally kept.
   *
   * They are the Supabase-connected
   * photograph index generated by the
   * original Sketchbook JavaScript.
   */
  .plates {
    display: block !important;

    width: min(
      1080px,
      calc(100vw - 40px)
    ) !important;

    max-width: 1080px !important;

    margin: 10px auto 0 !important;
    padding: 0 20px 34px !important;
  }

  .plates .section-label {
    display: block !important;
    margin-bottom: 14px !important;
  }

  .plate-list {
    display: block !important;

    width: 100% !important;

    list-style: none !important;
    margin: 0 !important;
    padding: 0 !important;

    border-top:
      1px solid
      rgba(43,39,33,.14) !important;
  }

  .plate-list li {
    display: block !important;
    width: 100% !important;
    margin: 0 !important;
    padding: 0 !important;
  }

  .plate {
    display: grid !important;

    grid-template-columns:
      3.4em
      minmax(0,1fr)
      auto !important;

    gap: 18px !important;

    align-items: baseline !important;

    width: 100% !important;

    padding:
      15px 4px !important;

    border: 0 !important;

    border-bottom:
      1px solid
      rgba(43,39,33,.14) !important;

    background:
      transparent !important;

    color:
      inherit !important;

    text-align:
      left !important;

    cursor:
      pointer !important;

    transition:
      background-color .22s ease,
      padding-left .22s ease !important;
  }

  .plate:hover,
  .plate[aria-current="true"] {
    background:
      rgba(255,252,244,.5) !important;

    padding-left:
      12px !important;
  }

  .plate .n {
    font-size: 12px !important;
    color:
      rgba(43,39,33,.36) !important;
    letter-spacing:
      .06em !important;
  }

  .plate .t {
    font-family:
      'Instrument Serif',
      Georgia,
      serif !important;

    font-size:
      clamp(19px,2.1vw,26px) !important;
  }

  .plate .p {
    font-size: 12.5px !important;

    color:
      rgba(43,39,33,.36) !important;

    letter-spacing:
      .08em !important;

    text-transform:
      uppercase !important;

    text-align:
      right !important;
  }

  .plate[aria-current="true"] .p {
    color:
      #9a6a3e !important;
  }

  @media (max-width: 700px) {
    .hero {
      padding:
        0 0 8px !important;
    }

    .sb-wrap {
      width: 100% !important;
      max-width: none !important;
    }

    .sb-3d {
      width:
        calc(100vw - 32px) !important;

      max-width: none !important;

      flex-basis:
        calc(100vw - 32px) !important;
    }

    .plates {
      width:
        calc(100vw - 24px) !important;

      padding:
        0 12px 26px !important;
    }

    .plate {
      grid-template-columns:
        2.8em
        minmax(0,1fr) !important;

      gap: 10px !important;
    }

    .plate .p {
      display: none !important;
    }

    .plate .t {
      font-size: 20px !important;
    }
  }
`;

function normalizePages(images) {
  return (images || [])
    .filter(
      (item) =>
        item?.image_url
    )
    .map(
      (item, index) => ({
        /*
         * This is the actual public
         * Supabase image URL.
         */
        file:
          item.image_url,

        title:
          item.title ||
          `MCA Photograph ${index + 1}`,

        place:
          item.category ||
          'MCA Department',
      })
    );
}

function replaceSketchbookPages(
  html,
  pages
) {
  let output = html;

  /*
   * The original Sketchbook uses
   * relative paths for its own assets.
   */
  if (
    !/<base\\s/i.test(
      output
    )
  ) {
    output =
      output.replace(
        '<head>',
        '<head><base href="/landing-pages/">'
      );
  }

  /*
   * Original:
   *
   * const DIR='meng-to-sketchbook/';
   *
   * We don't want Supabase URLs to
   * receive that prefix.
   */
  output =
    output.replace(
      "const DIR='meng-to-sketchbook/';",
      "const DIR='';"
    );

  /*
   * Find the original PAGES array.
   */
  const pagesStart =
    output.indexOf(
      'const PAGES=['
    );

  const pagesEndMarker =
    'PAGES.forEach(p=>p.url=DIR+p.file);';

  const pagesEnd =
    output.indexOf(
      pagesEndMarker,
      pagesStart
    );

  if (
    pagesStart !== -1 &&
    pagesEnd !== -1
  ) {
    /*
     * Convert the Supabase records
     * into the exact structure expected
     * by the original Sketchbook.
     */
    const serializedPages =
      JSON.stringify(
        pages
      ).replace(
        /</g,
        '\\u003c'
      );

    output =
      output.slice(
        0,
        pagesStart
      ) +
      `const PAGES=${serializedPages};\n` +
      output.slice(
        pagesEnd
      );

    /*
     * Every file supplied from Supabase
     * is already an absolute URL.
     */
    output =
      output.replace(
        pagesEndMarker,
        'PAGES.forEach(p=>p.url=p.file);'
      );
  } else {
    console.error(
      'MCA Sketchbook: original PAGES array was not found.'
    );
  }

  /*
   * Inject only visual CSS.
   *
   * The original animation JavaScript
   * remains untouched.
   */
  const styleBlock = `
    <style id="mca-sketchbook-style">
      ${MCA_EMBED_STYLE}
    </style>
  `;

  if (
    output.includes(
      '</head>'
    )
  ) {
    output =
      output.replace(
        '</head>',
        `${styleBlock}</head>`
      );
  }

  return output;
}

export default function BookGallery({
  images = [],
  loading = false,
  error = '',
}) {
  const iframeRef =
    useRef(null);

  const [
    sourceHtml,
    setSourceHtml,
  ] = useState('');

  const [
    sourceError,
    setSourceError,
  ] = useState('');

  const pages = useMemo(
    () =>
      normalizePages(
        images
      ),
    [images]
  );

  const srcDoc =
    useMemo(
      () => {
        if (
          !sourceHtml ||
          !pages.length
        ) {
          return '';
        }

        return replaceSketchbookPages(
          sourceHtml,
          pages
        );
      },
      [
        sourceHtml,
        pages,
      ]
    );

  const sendPages =
    useCallback(
      () => {
        const frame =
          iframeRef.current;

        if (
          !frame?.contentWindow ||
          !pages.length
        ) {
          return;
        }

        frame.contentWindow.postMessage(
          {
            type:
              'mca-sketchbook-pages',
            pages,
          },
          SKETCHBOOK_ORIGIN
        );
      },
      [pages]
    );

  useEffect(
    () => {
      let mounted = true;

      async function loadSketchbook() {
        try {
          setSourceError('');

          const response =
            await fetch(
              SKETCHBOOK_URL,
              {
                cache:
                  'no-store',
              }
            );

          if (
            !response.ok
          ) {
            throw new Error(
              `Sketchbook source returned ${response.status}.`
            );
          }

          const html =
            await response.text();

          if (
            mounted
          ) {
            setSourceHtml(
              html
            );
          }
        } catch (
          loadError
        ) {
          console.error(
            'Sketchbook source error:',
            loadError
          );

          if (
            mounted
          ) {
            setSourceError(
              'The sketchbook animation could not be loaded.'
            );
          }
        }
      }

      loadSketchbook();

      return () => {
        mounted = false;
      };
    },
    []
  );

  useEffect(
    () => {
      sendPages();
    },
    [sendPages]
  );

  if (
    loading
  ) {
    return (
      <div className="flex h-[600px] items-center justify-center">
        <div className="text-center">

          <div className="mx-auto h-7 w-7 animate-spin rounded-full border-2 border-[#c9784d]/25 border-t-[#c9784d]" />

          <p className="mt-4 text-sm font-semibold text-stone-700">
            Opening the sketchbook...
          </p>

          <p className="mt-1 text-xs text-stone-400">
            Loading photographs from the MCA archive.
          </p>

        </div>
      </div>
    );
  }

  if (
    error
  ) {
    return (
      <div className="flex h-[420px] items-center justify-center rounded-3xl border border-red-200 bg-red-50 px-6 text-center">
        <div>

          <h2 className="font-serif text-2xl text-stone-900">
            Gallery unavailable
          </h2>

          <p className="mt-2 text-sm text-red-700">
            {error}
          </p>

        </div>
      </div>
    );
  }

  if (
    !pages.length
  ) {
    return (
      <div className="flex h-[500px] items-center justify-center rounded-3xl border border-stone-200 bg-[#eee9df] px-6 text-center">
        <div className="max-w-md">

          <p className="text-[10px] font-bold uppercase tracking-[0.24em] text-stone-400">
            MCA Visual Archive
          </p>

          <h2 className="mt-2 font-serif text-3xl text-stone-900">
            The sketchbook is empty
          </h2>

          <p className="mt-3 text-sm leading-relaxed text-stone-500">
            Gallery photographs will appear here when they are uploaded through the administrator panel.
          </p>

        </div>
      </div>
    );
  }

  if (
    sourceError
  ) {
    return (
      <div className="flex h-[420px] items-center justify-center rounded-3xl border border-red-200 bg-red-50 px-6 text-center">
        <div>

          <h2 className="font-serif text-2xl text-stone-900">
            Sketchbook unavailable
          </h2>

          <p className="mt-2 text-sm text-red-700">
            {sourceError}
          </p>

        </div>
      </div>
    );
  }

  if (
    !srcDoc
  ) {
    return (
      <div className="flex h-[600px] items-center justify-center">
        <div className="text-center">

          <div className="mx-auto h-7 w-7 animate-spin rounded-full border-2 border-[#c9784d]/25 border-t-[#c9784d]" />

          <p className="mt-4 text-sm font-semibold text-stone-700">
            Preparing the book...
          </p>

        </div>
      </div>
    );
  }

  return (
    <div className="relative mx-auto w-full max-w-[1100px]">

      <iframe
        ref={iframeRef}
        title="MCA Department Sketchbook"
        srcDoc={srcDoc}
        onLoad={sendPages}
        sandbox="allow-scripts allow-same-origin allow-downloads"
        loading="eager"
        className="block h-[1080px] w-full border-0"
        style={{
          background:
            '#ece7dc',
        }}
      />

    </div>
  );
}